// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnOq1iJ8N7mpwLNNsXhpl-a40gMKnsu0',
    appId: '1:711184427721:web:YOUR_WEB_APP_ID',
    messagingSenderId: '711184427721',
    projectId: 'skynet-stationary',
    authDomain: 'skynet-stationary.firebaseapp.com',
    storageBucket: 'skynet-stationary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnOq1iJ8N7mpwLNNsXhpl-a40gMKnsu0',
    appId: '1:711184427721:android:98de4f70a0bc8f8f73fb18',
    messagingSenderId: '711184427721',
    projectId: 'skynet-stationary',
    storageBucket: 'skynet-stationary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnOq1iJ8N7mpwLNNsXhpl-a40gMKnsu0',
    appId: '1:711184427721:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '711184427721',
    projectId: 'skynet-stationary',
    storageBucket: 'skynet-stationary.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjnOq1iJ8N7mpwLNNsXhpl-a40gMKnsu0',
    appId: '1:711184427721:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '711184427721',
    projectId: 'skynet-stationary',
    storageBucket: 'skynet-stationary.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
